# Project: PM2.5
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = "PM2.5 0.o"
LINKOBJ  = "PM2.5 0.o"
LIBS     = -L"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/" -L"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/" -L"g:/计导homeworkdevc/dev-cpp/mingw32/mingw32/lib/" -L"g:/计导homeworkdevc/dev-cpp/mingw32/lib/" -L"G:/计导homeworkdevc/Dev-Cpp/MinGW32/lib" -L"G:/计导homeworkdevc/Dev-Cpp/MinGW32/mingw32/lib" -g3 -static
INCS     = -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
CXXINCS  = -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/mingw32" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/backward" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
BIN      = PM2.5.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Wall -Wextra -g3
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "$(BIN)" $(LIBS)

"PM2.5 0.o": PM2.5\ 0.c
	$(CC) -c "PM2.5 0.c" -o "PM2.5 0.o" $(CFLAGS) 
