# Project: 项目1
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 计算整数各位数字之和.o
LINKOBJ  = 计算整数各位数字之和.o
LIBS     = -L"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/" -L"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/" -L"g:/计导homeworkdevc/dev-cpp/mingw32/mingw32/lib/" -L"g:/计导homeworkdevc/dev-cpp/mingw32/lib/" -L"G:/计导homeworkdevc/Dev-Cpp/MinGW32/lib" -L"G:/计导homeworkdevc/Dev-Cpp/MinGW32/mingw32/lib" -g3 -static
INCS     = -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
CXXINCS  = -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/mingw32" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include/c++/backward" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/include" -I"g:/计导homeworkdevc/dev-cpp/mingw32/lib/gcc/mingw32/9.2.0/include-fixed"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Wall -Wextra -g3
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "$(BIN)" $(LIBS)

计算整数各位数字之和.o: 计算整数各位数字之和.c
	$(CC) -c 计算整数各位数字之和.c -o 计算整数各位数字之和.o $(CFLAGS) 
